title: Conference Title
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

email: aistats2019@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "/proceedings" # the subpath of your site, e.g. /blog/
github_username:  lawrennd

author:
  name: lawrennd

comments: false
style: dsa

ghub:
  edit: true
  repository: proceedings

# Build settings
markdown: kramdown
# change encoding for the generated output files to utf-8
encoding: utf-8

banner: resort.png

conference:
  draft: false # set to True if the programme is draft only.
  image: conference-venue.png
  hide_tentative: true
  proceedings:
    url: 
    show: false
  room: 
  venue: Conference venue
  venue_url: 
  location: City, Country
  full_name: Conference Full Name
  name: ConfAbbrv
  year: 20XX
  instance: 1st
  styling: International Conference on
  dates:
  - 1970-01-01
  - 1970-01-05
  submission: # Details of the submission site (e.g. CMT)
    show: False
    url: 
    name: 
  deadlines:
    - name: Submission server open
      type: submission
      date: 2018-09-14
    - name: Paper submission deadline
      type: submission
      text: Thursday, 4 October 2018 23:59 PDT
    - name: Author feedback deadline
      date: 2018-11-21
    - name: Paper decision notifications
      date: 2018-12-24
      type: decision
    - name: Registration open
      date: 2019-01-21
    - name: Early registration deadline
      date: 2019-02-16
    - name: Regular registration deadline
      date: 2019-03-16
    - name: Deadline for camera-ready papers
      date: 2019-02-25
  chairs:
  - type: Program Chairs
    people:
    - family: Surname
      given: Name
      url: 
      institute: University of Conference Organisation
    - family: Surname
      given: Name
      url: 
      institute: University of Conference Organisation
  - type: Local Chair
    people:
    - family: Surname
      given: Name
      url: 
      institute: University of Conference Organisation
  - type: Workflow Chairs
    people:
    - family: Surname
      given: Name
      url: 
      institute: University of Conference Organisation
    - family: Surname
      given: Name
      url: 
      institute: University of Conference Organisation
  - type: Publication Chairs
    people:
    - family: Surname
      given: Name
      url: 
      institute: University of Conference Organisation
  - type: Publicity Chair
    people:
    - family: Surname
      given: Name
      url: 
      institute: University of Conference Organisation
  sponsors:
  - name: Company 1
    logo: dr-logo-red.png
    url: 
    width: 250

plugins:
 - jekyll-feed
 - jekyll-seo-tag
